#!/usr/bin/env bash

NS="split"
IF="eno1"
VETH_TO="veth0" VETH_FROM="veth1"
VETH_FROM_IP="10.1.1.2" VETH_FROM_MASK="24"
VETH_TO_IP="10.1.1.1" VETH_TO_MASK="24"
DNS="1.1.1.1"

create() {
  # Create namespace
  ip netns add "$NS"

  ip netns exec "$NS" ip link set lo up

  ip link add "$VETH_TO" type veth peer name "$VETH_FROM"
  
  ip addr add "$VETH_TO_IP/$VETH_TO_MASK" dev "$VETH_TO"

  ip link set "$VETH_TO" up

  # Moving $VETH_FROM to namespace
  ip link set "$VETH_FROM" netns "$NS"

  ip netns exec "$NS" ip addr add "$VETH_FROM_IP/$VETH_FROM_MASK" dev "$VETH_FROM"

  ip netns exec "$NS" ip link set "$VETH_FROM" up
  ip -n "$NS" route add default dev "$VETH_FROM" via "$VETH_TO_IP"

  # Don't route to wg
  ip rule add from "$VETH_FROM_IP" table main priority 99

  # NAT
  iptables -t nat -A POSTROUTING -s "$VETH_TO_IP/$VETH_TO_MASK" -o "$IF" -j MASQUERADE
  iptables -A FORWARD -i "$IF" -o "$VETH_TO" -j ACCEPT
  iptables -A FORWARD -o "$IF" -i "$VETH_TO" -j ACCEPT

  # Custom DNS for namespace in case Wireguard specific DNS config
  mkdir -p /etc/netns/"$NS"
  echo "nameserver $DNS" > /etc/netns/"$NS"/resolv.conf
}

destroy() {
  rm -Rf /etc/netns/"$NS"

  iptables -t nat -D POSTROUTING -s "$VETH_TO_IP/$VETH_TO_MASK" -o "$IF" -j MASQUERADE
  iptables -D FORWARD -i "$IF" -o "$VETH_TO" -j ACCEPT
  iptables -D FORWARD -o "$IF" -i "$VETH_TO" -j ACCEPT

  ip rule delete from "$VETH_FROM_IP" table main priority 99

  ip link delete "$VETH_TO"

  ip netns delete "$NS"
}

if [[ "$1" == "--init" || "$1" == "-i" ]]; then 
  create
elif [[ "$1" == "--destroy" || "$1" == "-d" ]]; then
  destroy
elif [[ -n "$*" ]]; then
  if [[ -z "$(ip netns list | grep -P $NS'(?= \(id: \d+\))')" ]]; then
    echo "Cannot find stun namespace. (Did you initialize stun with --init ?)"
    exit 1
  fi
  ip netns exec "$NS" $@
else
  echo "(s)plit (tun)nel, a wireguard split tunnel script"
  echo
  echo "USAGE: "
  echo "stun --init -i | --destroy -d"
  echo
  echo "--init | -i	Must be run before using exec. Create a new network namespace for split tunneling, along with other stuff to make this all work." 
  echo "--destroy | -d	Destroys the network namespace for split tunneling."
  echo
  echo "stun COMMAND"
  echo
  echo "Run command in the split tunnel network namespace."
  echo
fi
